import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        playfair: ["var(--font-playfair)", "Georgia", "serif"],
        ui: ["var(--font-ui)", "system-ui", "sans-serif"],
        body: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
      },
      colors: {
        ink: "var(--ink)",
        paper: "var(--paper)",
        "warm-mid": "var(--warm-mid)",
        border: "var(--border)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        muted: "var(--muted-bg)",
        "muted-foreground": "var(--muted-foreground)",
        "muted-hover": "var(--muted-hover)",
        "muted-active": "var(--muted-active)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        "notion-default": "var(--notion-default)",
        "notion-default-bg": "var(--notion-default-bg)",
        "notion-gray": "var(--notion-gray)",
        "notion-gray-bg": "var(--notion-gray-bg)",
        "notion-brown": "var(--notion-brown)",
        "notion-brown-bg": "var(--notion-brown-bg)",
        "notion-orange": "var(--notion-orange)",
        "notion-orange-bg": "var(--notion-orange-bg)",
        "notion-yellow": "var(--notion-yellow)",
        "notion-yellow-bg": "var(--notion-yellow-bg)",
        "notion-green": "var(--notion-green)",
        "notion-green-bg": "var(--notion-green-bg)",
        "notion-blue": "var(--notion-blue)",
        "notion-blue-bg": "var(--notion-blue-bg)",
        "notion-purple": "var(--notion-purple)",
        "notion-purple-bg": "var(--notion-purple-bg)",
        "notion-pink": "var(--notion-pink)",
        "notion-pink-bg": "var(--notion-pink-bg)",
        "notion-red": "var(--notion-red)",
        "notion-red-bg": "var(--notion-red-bg)",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        md: "calc(0.5rem - 2px)",
        sm: "calc(0.5rem - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
